AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: CodeStar projectId used to associate new resources to team members
  CodeDeployRole:
    Type: String
    Description: IAM role to allow AWS CodeDeploy to manage deployment of AWS Lambda functions
  Stage:
    Type: String
    Description: The name for a project pipeline stage, such as Staging or Prod, for which resources are provisioned and deployed.
    Default: ''

Globals:
  Function:
    AutoPublishAlias: live
    DeploymentPreference:
      Enabled: true
      Type: Canary10Percent5Minutes
      Role: !Ref CodeDeployRole
  Api:
    # Allows an application running at https://digitize.aleonard.dev to call this API
    Cors:
      AllowMethods: "'OPTIONS,POST,GET'"
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'https://digitize.aleonard.dev'"

Resources:
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: DigitizeRestAPI
      Domain:
        DomainName: digitize-api1.aleonard.dev
        CertificateArn: arn:aws:acm:us-west-2:917159232232:certificate/ba2d0a69-0de2-44ff-b3bd-e3acef4c9122
        Route53:
          HostedZoneId: Z21QA4NBX4IRX8
      StageName: prod
      TracingEnabled: true
  StudentsGetAllFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DigitizeStudentsGetAll
      Handler: api/students/get.handler
      Runtime: python3.7
      MemorySize: 128
      Tracing: Active
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /students/
            Method: get
            RestApiId: !Ref RestApi
  StudentsPostFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DigitizeStudentsPost
      Handler: api/students/post.handler
      Runtime: python3.7
      MemorySize: 128
      Tracing: Active
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /students/
            Method: post
            RestApiId: !Ref RestApi
  StudentsOptionsAllFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DigitizeStudentsOptionsAll
      Handler: api/options.handler
      Runtime: python3.7
      MemorySize: 128
      Tracing: Active
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /students/
            Method: options
            RestApiId: !Ref RestApi
  StudentsGetStudentIDFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DigitizeStudentsGetStudentID
      Handler: api/students/studentid/get.handler
      Runtime: python3.7
      MemorySize: 128
      Tracing: Active
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /students/studentid/{StudentID}/
            Method: get
            RestApiId: !Ref RestApi
  StudentsGetCardIDFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DigitizeStudentsGetCardID
      Handler: api/students/cardid/get.handler
      Runtime: python3.7
      MemorySize: 128
      Tracing: Active
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /students/cardid/{CardID}/
            Method: get
            RestApiId: !Ref RestApi
  LambdaExecutionRole:
    Description: Creating service role in IAM for AWS Lambda
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'CodeStar-${ProjectId}-Execution${Stage}'
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [lambda.amazonaws.com]
          Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/CodeStar_${ProjectId}_PermissionsBoundary'
  DigitizeStudents:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: DigitizeStudents
      AttributeDefinitions:
        - AttributeName: CardID
          AttributeType: S
        - AttributeName: StudentID
          AttributeType: S
      KeySchema:
        - AttributeName: CardID
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: StudentID
          KeySchema:
            - AttributeName: StudentID
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Project
          Value: Digitize
        - Key: Name
          Value: DigitizeStudents
